### ISSUE TITLE
Error with text containing '@'

### ISSUE THREAD

**Issue by htopkill** [mittelmark/pantcl#1]
pantcl version V0.9.0

When using pandoc --filter pantcl.tapp with a text like 'foo @text bar', i have an error : 

=====  ERROR LOG ========
Path element 9: "t" not found
    while executing
"::rl_json::json get $jsonData blocks {*}$tkey"
    (procedure "walk" line 30)
    invoked from within
"walk $nkey $ind"
    (procedure "walk" line 21)
    invoked from within
"walk $nkey $ind"
    (procedure "walk" line 21)
    invoked from within
"walk $ckey $ind "
    (procedure "walk" line 40)
    invoked from within
"walk [list $i c $j]"
    (procedure "main" line 59)
    invoked from within
"main $jsonData"
    invoked from within
"puts -nonewline [main $jsonData]"
    (file "/home/myself/.bin/Xwriter/plugin/pantcl.tapp" line 1507)
Error running filter /home/myself/.bin/Xwriter/plugin/pantcl.tapp:
Filter returned error status 1

**Comment by mittelmark** [comment]
Thanks for the report, I tried to catch the error by checking first for key existence and then parsing.
Could you try out the build: https://github.com/mittelmark/pantcl/suites/11361055317/artifacts/584236575

You can rename it to pantcl.app if you like or just leave it as pantcl.bin

If this would be ok, I would adapt the download links.

**Comment by htopkill** [comment]
build V0.9.1 you provide solve the problem :-)
