### ISSUE TITLE
Error with filter-pipe

### ISSUE THREAD

**Issue by htopkill** [mittelmark/pantcl#2]
Error with filter-pipe on this document:   https://github.com/htopkill/test-only    file : docs.md

===  ERROR LOG ===
Error running filter /home/myself/.bin/Xwriter/plugin/pantcl.tapp:
Filter returned error status 1
[WARNING] Could not parse YAML metadata at line 3794 column 1: Unexpected '`'
couldn't execute "R": no such file or directory
    while executing
"open "|R -q --interactive --vanilla  2>@1" r+"
    (procedure "filter-pipe" line 26)
    invoked from within
"filter-pipe $c $d"
    (procedure "main" line 78)
    invoked from within
"main $jsonData"
    invoked from within
"puts -nonewline [main $jsonData] "
    (file "/home/myself/.bin/Xwriter/plugin/pantcl.tapp" line 1509)

**Comment by mittelmark** [comment]
Hmm,

the file/folder seems to be hidden, not public:  https://github.com/htopkill/test-only

You have R installed and in the path? Which system you are Linux/Windows?

Detlef

**Comment by htopkill** [comment]
oups, it's public now
i use linux, i don't have R installed

**Comment by mittelmark** [comment]
To use the pipe with R you need to have R installed -> https://www.r-project.org - probably I should add a check if the executable exists and give otherwise a hint in the document or just simply return the text as it is.

**Comment by mittelmark** [comment]
Ok, I got the point, there is no R code in the document but it still tries to execute it as a R -chunk ... Look into this ...

BTW: V is very interesting might be nice to have a V filter. Should be not that difficult.

**Comment by mittelmark** [comment]
I fixed the issue, that was not desired evaluation by accident. That reminds me on your previous suggestion to make the default evaluation mode to false. I did this now as well. So for evaluation the chunk option eval=1 or eval=true must be set or in the YAML header, like this 

```
tcl:
    eval: 1
```

May be you can check the attached executable. For me this works as well with V-documentation without problems:
[pantcl-0.9.9.zip](https://github.com/mittelmark/pantcl/files/10918457/pantcl-0.9.9.zip)

If this is all fine I would go version 1.0.0 in the near future. 

Thank you for the bug report.

**Comment by htopkill** [comment]
OK, it works now with V0.9.9
On my tcl application , i disable evaluation :  
set env(FILTEREVAL) 0;

For V code evaluation, i'm not sure it's a priority : May be i'm wrong, but in markdown document, i don't think a lot of people use tcl/python...code evaluation.  
I mainly use graphical evaluation, and your sqlite filter is also interesting

**Comment by mittelmark** [comment]
V code by the way can be already embedded:

Here an example:

```
` ``{.cmd file="hello.v" eval=true}
///usr/local/bin/v run $0 $@  2>&1 && exit 0
println("Hello V World!")
` ``
```

The space between the tickmarks should be removed.
