### ISSUE TITLE
low processing speed

### ISSUE THREAD

**Issue by htopkill** [mittelmark/pantcl#3]
The filters works on small document but introduce a high processing time with medium/high-sized document.
I have a difference of nearly 15 seconds with/without filters with an average laptop
This extra processing time append even if the document contains no code block

Is it possible to reduce this processing time with :
- Disable some filters ?
- Change the parsing strategy to apply your filters only on Code block ?

I have introduced your filters in my application : https://github.com/htopkill/Xwriter

**Comment by mittelmark** [comment]
I have some timeout in Tcl there to better syn the input and output channel. The default is probably to high, 100ms and inline code so for every code chunk. May be I make this smaller and an option for the YAML header. Probably it is not a good idea to mix, Octave, R and Python in one document as in my example. I think I will create a separate document for each language and then play with the after options, timeout the focus should be on Python and may be R.

https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/pantcl/master/lib/tclfilters/filter-pipe.html
Is a mix of R, Octave and Python code chunks

**Comment by mittelmark** [comment]
OK, I might have found the bottleneck, please try the attached binary. I need now 60times less time for files without any blocks with evaluation requirement:) Have not check it too much. I just moved a computation out of the forloop declaration before of it.

[pantcl-0.9.9.zip](https://github.com/mittelmark/pantcl/files/10922304/pantcl-0.9.9.zip)

**Comment by htopkill** [comment]
ouaahhh... that's day and night.  You solve the problem
I tested on several documents and i don't notice anymore a significant delay : 
That works on :
- Documents without code block
- Documents with lot of code block without code evaluation

I didn't test on document requiring lot of code evaluation with your filters but i don't think it will be a problem

My application + your filters rocks together !!

**Comment by mittelmark** [comment]
Great to hear that :) 
I will look still a little bit into the pipe filter as it can become sometimes messy if python and R and Octace are mixed and then make a 1.0.0 release.
Thanks a lot for your bug reports, you never can catch the nasty things alone.

**Comment by htopkill** [comment]
you're welcome
it's great to use your filters now in my tcl application. 
I was looking for lua filters, but didn't find something working correctly, whatever the destination format
In my application, I  added your licence, and included html help files. 
I will continue the test, but so far, so good

**Comment by mittelmark** [comment]
Ok, no more problems with this issue showed, up. Let's close the topic.
