### ISSUE TITLE
Question about eval=true

### ISSUE THREAD

**Issue by htopkill** [mittelmark/pantcl#4]
I have the feeling that with 0.9.9 version, for code/sqlite evaluation, you always need : 
- either eval=true
- or environmental FILTEREVAL = true

I prefer this way, but that means your documentation is not up-to-date ( eval=true by default in your documentation)

**Comment by mittelmark** [comment]
I think the HTML page should be up todate now:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/pantcl/master/lib/tclfilters/filter-sqlite.html

I changed the default as well to eval=false for the dot and the abc filter. I think here the default could be without too much danger to true, but it should be the same for all filters I think.
