### ISSUE TITLE
unexpected temporary files with sqlite/cmd filters

### ISSUE THREAD

**Issue by htopkill** [mittelmark/pantcl#5]
When using sqlite/cmd filters, you create files in the current folder.
As far as i understood, it's only temporary files that should be written in /tmp or $HOME/.cache/pantcl/ if possible
The 'file=...' should be reserved only if user want to redirect output to a permanent file, but i have the feeling you cannot make code evaluation without
if 'file=...' is absolutely necessary, may be you should authorize absolute path as 'file=/tmp/temp.c' ( I got an error when i tried: couldn't execute "./tmp/temp.c")

Note : i had problem with /tmp and ubuntu last time i tried ubuntu with my application. But .cache can be a good place for small files

**Comment by mittelmark** [comment]
I think I will try to use ~/.cache/pantcl, that is a good idea. There are still a few other places where there are temporary files created. I will look first into sqlite3 and cmd. If file=filename.r is requested that should be then in the current working directory I suggest.

**Comment by htopkill** [comment]
when i need to create a non essential file in current working dir, i usually give a name as tmp_xx or temp_xx or xxx.tmp
When i make some cleaning, i know i can delete them without problem

Note : i was septic about code evaluation, but i was wrong : it offers ton of possibilities. 
On my application (Xwriter), to avoid big issue with filters and debug easily, i disable them by default,  with a menu to enable them  ( If eval=false by default, it will be more safe, and i could enable them by default in the future )
I also think about integrate pantcl --GUI instead of a using a graphiz-only editor
Thank you

**Comment by mittelmark** [comment]
Here a version which should write all files requested with file="" into the cachedir, for cmd the cachdir can be changed in the meta data or on a per chunk setting using something like cachedir="." to take the current pwd. Should work with both sqlite and cmd

[pantcl-0.9.9b.zip](https://github.com/mittelmark/pantcl/files/10944660/pantcl-0.9.9b.zip)

**Comment by htopkill** [comment]
OK, it works as expected with/without cachedir="."
but I found 2 errors:

ERROR1 : 
///usr/bin/cc -o "${0%.c}" "$0" -lm && exec "./${0%.c}"
==>  do not work, but work with exec "${0%.c}"

ERROR2:
///usr/bin/g++ -o "${0%.cxx}" "$0" && exec "./${0%.cxx}"
==> do not work , even if i change to exec "${0%.cxx}"
fatal error: input file ‘/home/myself/.cache/pantcl/temp4.cpp’ is the same as output file
compilation terminated.
/home/myself/.cache/pantcl/temp4.cpp: 3: Syntax error: "(" unexpected
    while executing
"exec [file join [dict get $dict cachedir] [dict get $dict file]]"

**Comment by htopkill** [comment]
Just another addition
pantcl -v return V0.9.9 and not V0.9.9b

**Comment by mittelmark** [comment]
Hmm, for me your C and C++ code suggestions work, Please have a look at the updated manual page:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/pantcl/master/lib/tclfilters/filter-cmd.html

Find as well an updated version 0.9.10:

[pantcl-0.9.10.zip](https://github.com/mittelmark/pantcl/files/10947974/pantcl-0.9.10.zip)

**Comment by htopkill** [comment]
I got the problem

in your documentation, you indicate 
///usr/bin/g++ -o "${0%.cxx}" "$0" && exec "${0%.cxx}"

but , i'm a dumb and i have tried with

{.cmd  echo=false eval=true  file="temp.cpp"  }
///usr/bin/g++ -o "${0%.cxx}" "$0" && exec "${0%.cxx}"

it works only if  file="temp.cxx"

**Comment by mittelmark** [comment]
I updated the documentation file for C++ to indicate the file extension problem (and added as well Lua and Rust examples).

https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/pantcl/master/lib/tclfilters/filter-cmd.html

**Comment by htopkill** [comment]
Works for me with : 
- eval=true
- For rust , replace xx/.cargo/.. with  ///usr/bin/rustc 

Note: You code quicker than i can find new issue !!

I thought also about these embedded code filter : The problem is the possibility to have a malware/virus directly inside the document.  May be the 'v' document i gave you contains embedded code with malware  ??!!!
I think i will let the filter disabled by default on my application with only a per-session activation

**Comment by mittelmark** [comment]
The default is now eval=false for all filters as you suggested a few weeks before. So that should be not a problem anymore. If someone request eval: 1 in the document preamble or eval=true in the code chunk they should know what they are doing, hopefully.

**Comment by mittelmark** [comment]
Seems to be fixed as far as I can see. Thanks for the report.
